import { Geist, Geist_Mono, Rubik } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/components/NavbarCompnent";
import Footer from "@/components/Footer";
import Providers from "@/Providers";

const rubik = Rubik({
  weight: ["300", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rubik.className} antialiased`}>
        <NavbarComponent />
        <Providers>
          <main className="min-h-[calc(100vh-292px)]">{children}</main>
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
